name: Fetch API Data and Store in Azure PostgreSQL

on:
  schedule:
    - cron: "*/10 * * * *"  # Exécute le script toutes les 10 minutes
  workflow_dispatch:  # Permet un lancement manuel

jobs:
  fetch_and_store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: python script_data_api_trafic_urbain.py
